### ISSUE TITLE
Logging service

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#10]
### Description
As a bot manager, I'd want to view a backlog of all actions my discord bot has undertaken on my website.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to receive log data from the discord bot
- [x] Should be able to retrieve logs for a corresponding user
 
### Tasks
- [x] _TBA_ Create API endpoints to receive data from Discord bot
- [x] _TBA_ Create API endpoints for the website to query so it can view data
- [x] _TBA_ Create Database saving features
