### ISSUE TITLE
Discord Bot Actions overview

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#12]
### Description
As a bot manager, I'd like to be able to have an overview of all actions my discord bot undertakes, so I know exactly what is going on.
 
### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to log all actions to the logging service
 
Also, here are a few points that need to be addressed:
 
- Constraint 1: Should use a single template for all the logs to send
 
### Tasks
- [ ] _TBA_ Add Logging functionality to commands and triggers
- [x] _TBA_ Create helper class for logging to external service
- [x] _TBA_ Add Zuul for dynamic routing and load-balancing
