### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#2]
### Description
As a bot manager, I'd like to be able to securely log into the application, in order to know that my dashboard and bot are always safe.
 
### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to register a new account
- [x] Should be able to remember the login session when application shuts down
- [x] Should be able to change password when not using external provider login
- [x] Should be able to login using a provider like google
 
### Tasks
- [x] _TBA_ Secure pages that require authentication
- [x] _TBA_ Create login flow
