### ISSUE TITLE
Bot Configuration & Management

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#21]
### Description
As a bot manager, I'd like to be able to dynamically configure parameters in my bot like banned words, regex, bot token etc., in order to customize my bot to my likings and to always keep it functional.
 
### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should have a general overview of the different settings that are changeable
- [ ] Should be able to change settings and see them reflected on the bot in 30 seconds
- [ ] Should be able to store my bot token
 
Also, here are a few points that need to be addressed:
 
1. Constraint 1: Must be authorized to manage the bot settings
2. Constraint 2: Settings must be accessible from the dashboard
 
### Tasks
- [ ] _TBA_ Create settings page with a general overview
- [ ] _TBA_ Create receiving API for the service
- [ ] _TBA_ Create sending API for the service
- [ ] _TBA_ Create storage functionality for holding bot configurations
