### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#3]
### Description
As a bot manager, I'd like to have a general overview of permissions and features I can control, in order to quickly manage my disccord bot. 
 
### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to register bot under its own token and add it to any server the bot manager needs
- [ ] Should be able to switch between guilds (per guild settings) 
- [ ] Should be able to add/remove words from the automod list 
- [ ] Should be able to add multiple Regular Expressions to filter URL's or other content
- [ ] Should have a general overview available of times users were warned
 
Also, here are a few points that need to be addressed:
 
1. Constraint 1: Must be authorized to manage and view
2. Constraint 2: Must have a registered and verified bot token to work
 
### Tasks
- [ ] _TBA_ Create dashboard page
- [ ] _TBA_ Get overview of the different guilds
- [ ] _TBA_ Add RegEx and word fields for automodding
- [ ] _TBA_ Create overview of users
