### ISSUE TITLE
Bans, Warnings & Appeal System

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#4]
### Description
As a bot manager, I'd like users that have been previously banned to be able to appeal their ban, in order to give them information on their ban and to have a backlog of times where users were violating the rules.
 
### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should have an overview of people that are trying to appeal their bans
- [ ] Should be able to quickly see what a user has done when clicking on their name
- [ ] Should be able to send information to the user using the bot
- [ ] Should be able to unban the convicted user if ban was deemed wrongful
 
Also, here are a few points that need to be addressed:
 
1. Constraint 1: Must be authorized to see appeal system
2. Constraint 2: Must be accessible from the dashboard
 
### Tasks
- [ ] _TBA_ Create appeal page with appeals overview
- [ ] _TBA_ Create user summary system
- [ ] _TBA_ Create communication to send info to user
- [ ] _TBA_ Create unban functionality
