### ISSUE TITLE
Discord bot functionality

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#5]
### Description
As a bot manager, I'd need to easily deploy a new bot with all the moderation features, in order to manage my guilds and users.
 
### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to auto deploy to the web
- [x] Should have all the automod features mentioned in previous issues
- [x] Should be easily updateable for the developer and auto redeploy once an update has completed
- [x] Should be able to register on the eureka server
 
Also, here are a few points that need to be addressed:
 
1. Constraint 1: can not auto register a new bot in discord so will have to manually enter the token and then start up the bot
2. Constraint 2: Should be able to reboot and start or stop whenever bot manager deems it necessary
 
### Tasks
- [x] _TBA_ Create Discord bot
- [x] _TBA_ Create Automod features
- [x] _TBA_ Create Eureka connection calls
- [x] _TBA_ Create deployment and update pipeline
