### ISSUE TITLE
API Security

### ISSUE THREAD

**Issue by OwendB1** [FHICT-S-Owen/DiscordBotManager#6]
### Description
As a developer, I'd like to have secure API communication between my microservices, in order to keep my client's info safe.
 
### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to send requests without leaking information
- [ ] Should only get responses back when unique identifier/credentials match
 
### Tasks
- [ ] _TBA_ Secure API's using https protocol instead of http
- [ ] _TBA_ Add unique identifier requirement / login credential requirement to API's in order to get a response
